version: "3.8"
services:
  dev-db:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: yt-favs
    networks:
      - ytnetwork
  test-db:
    image: postgres:14.5
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: yt-favs
    networks:
      - ytnetwork
networks:
  ytnetwork:

